export const UPDATE_DISPOSABLE_POINTS = "UPDATE_DISPOSABLE_POINTS"
export const UPDATE_LAYERS = "UPDATE_LAYERS"
export const UPDATE_VIEWPORT = "UPDATE_VIEWPORT"
export const UPDATE_VIEWPORT_SIZE = "UPDATE_VIEWPORT_SIZE"